### ISSUE TITLE
Provide arguments which apply changes to aerostat metadata (e.g. change aliases)

### ISSUE THREAD

**Issue by gmcquillan** [urbanairship/aerostat#5]
There needs to be a call which allows users to change certain types of metadata in a simple way. 

It might look something like this:

As run from the host you're changing the alias info for:
aerostat --change-aliases 'new-alias'

As run from another (probably admin) server:
aerostat --change-aliases 'new-alias' --host 'hostname-x'

This could work for other meta-data, too, but changing service or service type might make naming conflicts if the hostname doesn't also change via pick_hostname().

**Comment by MrAlias** [comment]
Closing to inform of project abandonment.
